### ISSUE TITLE
Data investigation notes

### ISSUE THREAD

**Issue by jamiegcan** [GoGroGlo/a-place-for-salvador-allende#6]
### Stats for visualization
- [x] Bar chart of number of places per `region`
- [x] Bar chart of number of places per `country`
- [x] Bar chart of number of places per `type` 
- [x] Bar chart of number of places: Chile vs. rest of the world
- [x] Map of pins 
- [x] Timeline of places built per month and year (only when `oldest_known_source` contains `desc`; annotate 26 June 2008 and other relevant dates)
- [x] Earliest place that was named after Allende
- [x] Most quoted lines from Allende (especially from the last speech) - kinda done. Hard to quantify using the `desc` data, but there is one obviously most quoted line from Allende.

Main filter for determining extant vs. non-extant Allende places: if `former_name` does not contain `Allende` AND `verified_in_maps` = 1, then it is extant

### Who were building things for Salvador Allende?
Expand and provide examples for each section:
- [x] Socialists
- [x] Democrats
- [x] Chileans

### Variations on a theme: How was Salvador Allende portrayed?
Not implemented as its own section but instead added as notes in the dataviz section
- [x] As a physician for the people (see hospitals, especially in Central America)
- [x] As a martyr for the masses (connect this to the section on how he died)
- [x] Great avenues

### How did Salvador Allende die, really?
- Make sense of what I've gathered so far not from a historical perspective ("How did Allende die?") but from a psychological perspective ("Why would people believe that Allende died a certain way?")

### To do
- [x] Fix broken images by changing their extension from `.jpeg` to `.jpg`
- [x] Translate http://www.memoriachilena.gob.cl/602/w3-article-799.html#ui-id-3 add add this to the section on Who was Salvador Allende 
- [x] Add technical notes on the data in the Readme instead of the data investigation page

**Comment by GoGroGlo** [comment]
We're prolly done for this year
